# Generated by Django 5.0 on 2023-12-19 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(default='login', max_length=10, verbose_name='Login')),
                ('password', models.CharField(default='password', max_length=10, verbose_name='Password')),
                ('email', models.EmailField(default='login@mail.com', max_length=30, verbose_name='Email')),
                ('phone', models.CharField(default='phone', max_length=20, verbose_name='Phone')),
                ('date_of_birth', models.DateTimeField(default='2000-01-01T00:00:00Z', verbose_name='Date of birth')),
                ('location', models.CharField(choices=[('location1', 'Location 1'), ('location2', 'Location 2')], max_length=100, verbose_name='Location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
