# Generated by Django 5.0 on 2023-12-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_category_userprofile_has_declined_shipping_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(choices=[('location1', 'Дніпро'), ('location2', 'Павлоград')], max_length=100, verbose_name='Location'),
        ),
    ]
