# Generated by Django 5.0 on 2023-12-21 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_product_shipping_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shipping_cost',
        ),
    ]
